FROM nginx:alpine

COPY index.html /usr/share/nginx/html/
COPY BarrackMap.js /usr/share/nginx/html/
COPY NutritionLegend.js /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
