global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mqtt-ingest'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mqtt-ingest:8081']

  - job_name: 'nutrition-rf'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['nutrition-rf:8082']

  - job_name: 'outbreak-satscan'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['outbreak-satscan:8083']

  - job_name: 'alert-broker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['alert-broker:8080']
